<a href="https://colab.research.google.com/github/sandeepa-oraon/DataAnalyses/blob/main/numpy/np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

creating 1D array

In [ ]:
arr= np.array([1, 2,3 ,4])
display(arr)

array([1, 2, 3, 4])

creating 2D array

In [ ]:
arr2= np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


creating 3D array

In [ ]:
arr3= np.array([[[1, 2, 3],
                 [2, 3, 4]],
                 [[3, 4, 5],
                  [2,3,1]]])
print(arr3)

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [2 3 1]]]


creating array from tuple

In [ ]:
arr4= np.array((1, 4, 2))
print(arr4)

[1 4 2]


Accessing the array element

In [8]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

In [10]:
#particular cell
print(arr[3][1])

-7.0


In [11]:
#2nd row, entire column
print(arr[2, :])

[2.6 0.  7.  8. ]


In [13]:
#entire row, 3 column
print(arr[:, 3])

[4. 0. 8. 2.]


In [14]:
#1st 2 row and alternate column(0 & 2)
print(arr[:2, ::2])

[[-1.  0.]
 [ 4.  6.]]
