<a href="https://colab.research.google.com/github/sandeepa-oraon/DataAnalyses/blob/main/numpy/np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

creating 1D array

In [2]:
arr= np.array([1, 2,3 ,4])
display(arr)

array([1, 2, 3, 4])

creating 2D array

In [5]:
arr2= np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


creating 3D array

In [6]:
arr3= np.array([[[1, 2, 3],
                 [2, 3, 4]],
                 [[3, 4, 5],
                  [2,3,1]]])
print(arr3)

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [2 3 1]]]


creating array from tuple

In [7]:
arr4= np.array((1, 4, 2))
print(arr4)

[1 4 2]
