<a href="https://colab.research.google.com/github/sandeepa-oraon/DataAnalyses/blob/main/numpy/np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

creating 1D array

In [ ]:
arr= np.array([1, 2,3 ,4])
display(arr)

array([1, 2, 3, 4])

creating 2D array

In [ ]:
arr2= np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


creating 3D array

In [ ]:
arr3= np.array([[[1, 2, 3],
                 [2, 3, 4]],
                 [[3, 4, 5],
                  [2,3,1]]])
print(arr3)

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [2 3 1]]]


creating array from tuple

In [15]:
arr4= np.array((1, 4, 2))
print(arr4)

[1 4 2]


Accessing the array element

In [ ]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

In [ ]:
#particular cell
print(arr[3][1])

-7.0


In [ ]:
#2nd row, entire column
print(arr[2, :])

[2.6 0.  7.  8. ]


In [ ]:
#entire row, 3 column
print(arr[:, 3])

[4. 0. 8. 2.]


In [ ]:
#1st 2 row and alternate column(0 & 2)
print(arr[:2, ::2])

[[-1.  0.]
 [ 4.  6.]]


###array operations

In [17]:
a = np.array([[1, 2],
              [3, 4]])

# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

In [18]:
print(a+b)

[[5 5]
 [5 5]]


In [19]:
print(a-b)

[[-3 -1]
 [ 1  3]]


In [21]:
print(a*b)

[[4 6]
 [6 4]]


In [22]:
print(a/b)

[[0.25       0.66666667]
 [1.5        4.        ]]


In [23]:
print(a.sum())

10
